"""add reels table

Revision ID: 12812087d3d2
Revises: 4dcd657afadf
Create Date: 2025-10-29 01:15:06.358639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12812087d3d2'
down_revision = '4dcd657afadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reel_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reel_id'], ['reel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reel_comment')
    # ### end Alembic commands ###
