"""add AIHistory table

Revision ID: 410add2b7fe9
Revises: 12812087d3d2
Create Date: 2025-10-29 17:25:37.268054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410add2b7fe9'
down_revision = '12812087d3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_history')
    # ### end Alembic commands ###
