"""Add block, follow, report models

Revision ID: 4393a0e9d6f6
Revises: 5e37901d936e
Create Date: 2025-10-31 04:05:50.807731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4393a0e9d6f6'
down_revision = '5e37901d936e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privacy_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terms_of_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='_user_block_unique')
    )
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='_user_follow_unique')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_participant_room_user'))

    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_chatroom_created'))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_comment_created_at'))
        batch_op.drop_index(batch_op.f('idx_comment_post_id'))
        batch_op.drop_index(batch_op.f('idx_comment_user_id'))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_message_created_at'))
        batch_op.drop_index(batch_op.f('idx_message_room_created'))
        batch_op.drop_index(batch_op.f('idx_message_room_id'))
        batch_op.drop_index(batch_op.f('idx_message_sender_id'))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_post_created_at'))
        batch_op.drop_index(batch_op.f('idx_post_user_created'))
        batch_op.drop_index(batch_op.f('idx_post_user_id'))

    with op.batch_alter_table('reel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_reel_created_at'))
        batch_op.drop_index(batch_op.f('idx_reel_likes_count'))
        batch_op.drop_index(batch_op.f('idx_reel_user_id'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_created'))
        batch_op.drop_index(batch_op.f('idx_user_email'))
        batch_op.drop_index(batch_op.f('idx_user_username'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_created'), ['created_at'], unique=False)

    with op.batch_alter_table('reel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_reel_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_reel_likes_count'), ['likes_count'], unique=False)
        batch_op.create_index(batch_op.f('idx_reel_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_post_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_post_user_created'), ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_post_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_message_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_message_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_message_room_created'), ['room_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_message_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_comment_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_comment_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_comment_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_chatroom_created'), ['created_at'], unique=False)

    with op.batch_alter_table('chat_participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_participant_room_user'), ['room_id', 'user_id'], unique=False)

    op.drop_table('report')
    op.drop_table('follow')
    op.drop_table('block')
    op.drop_table('terms_of_service')
    op.drop_table('privacy_policy')
    # ### end Alembic commands ###
