"""Add database indexes and connection pooling

Revision ID: 5e37901d936e
Revises: 410add2b7fe9
Create Date: 2025-10-30 15:56:15.150851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e37901d936e'
down_revision = '410add2b7fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_participant', schema=None) as batch_op:
        batch_op.create_index('idx_participant_room_user', ['room_id', 'user_id'], unique=False)

    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.create_index('idx_chatroom_created', ['created_at'], unique=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index('idx_comment_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_comment_post_id', ['post_id'], unique=False)
        batch_op.create_index('idx_comment_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index('idx_message_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_message_room_created', ['room_id', 'created_at'], unique=False)
        batch_op.create_index('idx_message_room_id', ['room_id'], unique=False)
        batch_op.create_index('idx_message_sender_id', ['sender_id'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('idx_post_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_post_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_post_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('reel', schema=None) as batch_op:
        batch_op.create_index('idx_reel_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_reel_likes_count', ['likes_count'], unique=False)
        batch_op.create_index('idx_reel_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_user_created', ['created_at'], unique=False)
        batch_op.create_index('idx_user_email', ['email'], unique=False)
        batch_op.create_index('idx_user_username', ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_username')
        batch_op.drop_index('idx_user_email')
        batch_op.drop_index('idx_user_created')

    with op.batch_alter_table('reel', schema=None) as batch_op:
        batch_op.drop_index('idx_reel_user_id')
        batch_op.drop_index('idx_reel_likes_count')
        batch_op.drop_index('idx_reel_created_at')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('idx_post_user_id')
        batch_op.drop_index('idx_post_user_created')
        batch_op.drop_index('idx_post_created_at')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index('idx_message_sender_id')
        batch_op.drop_index('idx_message_room_id')
        batch_op.drop_index('idx_message_room_created')
        batch_op.drop_index('idx_message_created_at')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index('idx_comment_user_id')
        batch_op.drop_index('idx_comment_post_id')
        batch_op.drop_index('idx_comment_created_at')

    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.drop_index('idx_chatroom_created')

    with op.batch_alter_table('chat_participant', schema=None) as batch_op:
        batch_op.drop_index('idx_participant_room_user')

    # ### end Alembic commands ###
